theme: jekyll-theme-cayman
title: ЄДУМКИ
description: Колекція засобів мислення та конструкції, які допоможуть Вам вирішити проблеми, приймати рішення та розуміти системи
show_downloads: false
github:
  is_project_page: false
